spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/lfey
    username: lfey_user
    password: lfey_password
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: localhost
    port: 5672
    username: root
    password: werpipl15
  cache:
    type: redis
    redis:
      cache-null-values: false
logging:
  file:
    name: user-service.log
  level:
    org.springframework: info
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
fanout:
  user_fanout: user_events_fanout
queue:
  messenger: messenger_queue
  notification: email_verification
token:
  signing:
    key: 32a8970858ce663ac2436dbdc7379f910733354be586b7a9751d465f411e3037edd76e3041e652aadbd675f473ad730275a7305f90f1dadd2e51848575af8efd
server:
  port: 8181