spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/lfey
    username: lfey_user
    password: lfey_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: localhost
    port: 5672
    username: root
    password: werpipl15
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
fanout:
  user_fanout: user_events_fanout
queue:
  messenger: messenger_queue
  notification: not
